#include <jni.h>
#include <fbjni/fbjni.h>
#include "NitroMapClusterOnLoad.hpp"

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, [] {
    // Register all NitroMapCluster HybridObjects (generated by nitrogen)
    margelo::nitro::nitromapcluster::registerAllNatives();
  });
}
